### ISSUE TITLE
UI code files

### ISSUE THREAD

**Issue by Irfanulhaq1991** [SEAbdulbasit/TravelApp-KMP#1]
@SEAbdulbasit Couldn't find any UI file in the android or IoS app. am I missing something?

**Comment by SEAbdulbasit** [comment]
UI is in shared module.

**Comment by Irfanulhaq1991** [comment]
Could you please also elaborate on why should one opt compose over swift UI? It would be nice if you could also provide your learning resources as a reference in the read me.

**Comment by pablichjenkov** [comment]
> Could you please also elaborate on why should one opt compose over swift UI?

I would say maintainability. There is only one code base. Otherwise, you have to maintain 2 ui sources. On another hand, using swiftui, you can still share common business logic code. 
So, personally I don't see any other advantage than maintainability, I might be wrong.
