### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by amolaksingh** [SEAbdulbasit/TravelApp-KMP#7]
When I click on france tab app is crashing.

**Comment by SEAbdulbasit** [comment]
Yes, there was a crash on the Android when clicked on France. On Android, there was an error in loading a big bitmap. I have removed the first image and now the crash should be gone. 
I am adding some image loading library to handle the memory.

Do a pull and let me know if the issue still exist.

**Comment by SEAbdulbasit** [comment]
Closing this issue.
